obj-m := wilc-sdio.o
ccflags-y += -I$(src)/ -DWILC_ASIC_A0 -DWILC_DEBUGFS

wilc-objs := wilc_wfi_cfgoperations.o wilc_netdev.o wilc_mon.o \
			wilc_hif.o wilc_wlan_cfg.o wilc_debugfs.o \
			wilc_wlan.o sysfs.o wilc_bt.o

wilc-sdio-y := wilc_sdio.o ${wilc-objs}

wilc-spi-y := wilc_spi.o ${wilc-objs}
